[superlink]
default = "local-simulation"

[superlink.local]
address = ":local:"

[superlink.local-simulation]
address = ":local-in-memory:"
options.num-supernodes = 10
options.backend.name = "ray"
options.backend.client-resources.num-cpus = 1
options.backend.client-resources.num-gpus = 0.0
